### ISSUE TITLE
guides: sort alphabetical order

### ISSUE THREAD

**Issue by IngolfSchmitt** [Werdenfels-Gymnasium/help#74]
You should sort the topics in alphabetical order

**Comment by DevVersion** [comment]
IMO, we should sort the guides dynamically through the frontend code. This won't need a manual sort. Thoughts?

**Comment by gilgda** [comment]
A manual sort wouldn´t be a problem ;). I could sort them after adding the Thunderbird account setup to guides.json

**Comment by DevVersion** [comment]
@gilgda I prefer a automatic sort, this would save much time and is much more dynamic.

Thanks for your offer anyway :smile:

**Comment by gilgda** [comment]
Ok :+1:

**Comment by DevVersion** [comment]
Will be addressed via V2
