### ISSUE TITLE
Quotaüberschreitung

### ISSUE THREAD

**Issue by IngolfSchmitt** [Werdenfels-Gymnasium/help#95]
Hallo an das fleißige Team,
Eine Hilfe zum Auffinden platzverschwendender Dateien auf Grund von Quota-Überschreitungen wäre noch eine tolle Sache.
vgl.:
http://www.linuxmuster.net/wiki/anwenderwiki:scripting:quota
In Kombination mit der QuotaAnzeige beim Login könnte man sogar gleich anzeigen wo die großen Platzverschwender liegen.

**Comment by DevVersion** [comment]
Ups falscher Knopf 😳 @Eisphoenix hat gesagt das er schon daran arbeitet 👌🏻
